export enum ACTION_TYPES {
  INITIAL_LOAD = 'INITIAL_LOAD',
  APP_BUSYTOGGLE = 'APP_BUSYTOGGLE',
  APP_INVOICE_FILTERSUPDATED = 'APP_INVOICE_FILTERSUPDATED',
  APP_FILTERUPDATED = 'APP_FILTERUPDATED',

  MODELS_UPDATED = 'MODELS_UPDATED',

  CONFIG_FETCHED = 'CONFIG_FETCHED',
  CONFIG_UPDATE = 'CONFIG_UPDATE',
  USERS_FETCHED = 'USERS_FETCHED',
  USER_UPDATE = 'USERS_UPDATE',
  ROLES_FETCHED = 'ROLES_FETCHED',
  ROLE_UPDATE = 'ROLE_UPDATE',

  CLIENTS_FETCHED = 'CLIENTS_FETCHED',
  /** Client inserts are also done with update */
  CLIENT_UPDATE = 'CLIENT_UPDATE',

  INVOICES_FETCHED = 'INVOICES_FETCHED',
  INVOICE_DELETED = 'INVOICE_DELETED',
  INVOICE_UPDATED = 'INVOICE_UPDATED',
  INVOICE_EMAILED = 'INVOICE_EMAILED',

  CONSULTANTS_FETCHED = 'CONSULTANTS_FETCHED',
  CONSULTANT_UPDATE = 'CONSULTANT_UPDATE',

  PROJECTS_FETCHED = 'PROJECTS_FETCHED',
  PROJECT_UPDATE = 'PROJECT_UPDATE',
  PROJECT_DELETE = 'PROJECT_DELETE',
  PROJECTS_MONTH_FETCHED = 'PROJECTS_MONTH_FETCHED',
  PROJECTS_MONTH_UPDATE = 'PROJECTS_MONTH_UPDATE',
  PROJECTS_MONTH_DELETE = 'PROJECTS_MONTH_DELETE',
  PROJECTS_MONTH_ATTACHMENTS_UPDATE = 'PROJECTS_MONTH_ATTACHMENTS_UPDATE',
  PROJECTS_MONTH_INVOICE_CREATED ='PROJECTS_MONTH_INVOICE_CREATED',
  PROJECTS_MONTH_OVERVIEWS_FETCHED ='PROJECTS_MONTH_OVERVIEWS_FETCHED',
  PROJECTS_MONTH_OVERVIEWS_UPDATE ='PROJECTS_MONTH_OVERVIEWS_UPDATE',
  PROJECTS_MONTH_OVERVIEWS_DELETE ='PROJECTS_MONTH_OVERVIEWS_DELETE',
}
